<div class="row">

    <div class="col-lg-3 text-center">
        <p class="container" id="output"  style="color:white;"><?php $this->flashSession->output() ?></p> 
        <h1 class="my-4 " style="font-size:30px;"> <img height="120px" src="<?= $this->url->getBaseUri(); ?>public/img/cad2.png"></h1> 

        <div class="list-group">
            <form action="" method="">
                <input type="text" size="25px" placeholder="Nom du livre recherché..." id="search" class="form-control" required />
                
            </form>
        </div>
        <br/>
        

    </div>

    <h4><b>Espace Administrateur</b></h4>
    <div class="col-lg-8">

        <h1 class="my-4 btn btn-block btn-primary " id="photo"  data-toggle="collapse" data-target="#save"  style=""> 
            <i style="font-size:20px;z-index:10;" class="fa fa-3x fa-plus"></i><b> Ajouter un livre</b>
        </h1>

        <form action="principal" method="post" enctype="multipart/form-data" >
            <div class="collapse" id="save">




                <input type="text" size="25" class="form-control" name="titre" placeholder="Titre du livre..." required>
                <br/>

                <textarea type="text" size="200" class="form-control" name="description" placeholder="Resumé du livre" required></textarea>
                <br/>

                <input type="text" size="25" class="form-control" name="auteur" placeholder="Auteur..." required>
                <br/>

                <h6><b>Catégorie: </b></h6><select name="categorie" class="form-control">
                    <?php foreach ($categories as $value): ?>
                        <option value="<?= $value->getIdCat() ?>"> <?= $value->getLibCat() ?> </option>
                    <?php endforeach; ?>

                </select>
                <br/>



                <div class="col-md-6 mb-4">
                    <h6><b>Photo de couverture du livre:</b></h6>
                    <label class="nav">
                        <i style="font-size:40px;" class=" col-sm-1 fa fa-2x fa-image"></i><input type="file" name="cover" style="display: none;"/>
                    </label>    
                </div>  

                <div class="col-md-6 mb-4">
                    <h6><b>Selectionner le livre (format TXT ou PDF ou WORD):</b></h6>
                    <label class="nav">
                        <i style="font-size:40px;" class=" col-sm-1 fa fa-2x fa-folder-open"></i><input type="file" name="lien" style="display: none;" multiple=""/>
                    </label>   
                </div> 

                <br/>
                <input type="submit" class="btn btn-lg btn-primary" value="Envoyer" required><br/>
                <br/>


            </div>
        </form>

        <h1 class="my-4 btn btn-block btn-primary " id="proposition"  data-toggle="collapse" data-target="#invitation"  style=""> 
            <i style="font-size:20px;z-index:10;" class="fa fa-3x fa-check"></i><b> Accepter suggestions</b>
        </h1>


        <div class="collapse" id="invitation">

            <table class="table table-striped table-inverse">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nom du livre</th>
                        <th>Nom de l'auteur</th>
                        <th>Utilisateur</th>
                        <th>Date d'ajout</th>
                        <th>Status</th>

                    </tr>
                </thead>

                <tbody id="loadpro">


                </tbody>
            </table>
            <button type="button" id="proload" value="" class="btn btn-info"><i class="fa fa-1x fa-eye"></i> Voir plus</button>
        </div>


        <h1 class="my-4 btn btn-block btn-primary " id="Li"  data-toggle="collapse" data-target="#livre"  style=""> 
            <i style="font-size:20px;z-index:10;" class="fa fa-3x fa-list"></i><b> Liste des livres</b>
        </h1>


        <div class="collapse" id="livre">

            <table class="table table-striped table-inverse">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nom du livre</th>
                        <th>Cover</th>
                        <th>Nom de l'auteur</th>
                        <th>Description</th>
                        <th>Status</th>

                    </tr>
                </thead>

                <tbody id="loadlivre">

                </tbody>
            </table>
            <button type="button" id="livreload" value="" class="btn btn-info"><i class="fa fa-1x fa-eye"></i> Voir plus</button>
        </div>
        <form action="update" method="post" enctype="multipart/form-data" >
            <div class="collapse" id="update">


                <div id="modif">



                </div>
                <br/>
                <h6><b>Catégorie: </b></h6><select name="categorie" class="form-control">
                    <?php foreach ($categories as $value): ?>
                        <option value="<?= $value->getIdCat() ?>"> <?= $value->getLibCat() ?> </option>
                    <?php endforeach; ?>

                </select>
                <br/>



                <div class="col-md-6 mb-4">
                    <h6><b>Photo de couverture du livre:</b></h6>
                    <label class="nav">
                        <i style="font-size:40px;" class=" col-sm-1 fa fa-2x fa-image"></i><input type="file" name="cover" style="display: none;"/>
                    </label>    
                </div>  

                <div class="col-md-6 mb-4">
                    <h6><b>Selectionner le livre (format TXT ou PDF ou WORD):</b></h6>
                    <label class="nav">
                        <i style="font-size:40px;" class=" col-sm-1 fa fa-2x fa-folder-open"></i><input type="file" name="lien" style="display: none;" multiple=""/>
                    </label>   
                </div> 

                <br/>
                <input type="submit" class="btn btn-lg btn-primary" value="Envoyer" required><br/>
                <br/>


            </div>
        </form>


    </div>

</div>
<script>
    $(document).ready(function () {


        var pro = 0;
        var livre = 0;
        function getresultpro(url) {
            $.ajax({
                url: url,
                type: "GET",
                data: {rowcount: $("#rowcountpro").val()},
                beforeSend: function () {
                    $('#load').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeIn(0);
                },
                complete: function () {
                    $('#load').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeOut(0);
                },
                success: function (data) {
                    $("#loadpro").append(data);
                },
                error: function () {}
            });
        }

        $("#proposition").click(function () {


            if (pro == 0) {

                $.ajax({
                    url: "<?= $this->url->get("admin/propositionload") ?>",
                    type: 'GET',
                    beforeSend: function () {
                        $('#load').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeIn(0);
                    },
                    complete: function () {
                        $('#load').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeOut(0);
                    },
                    success: function (data) {
                        $("#loadpro").append(data);

                    }


                });
                pro = 1;
            }
        });

        $("#proload").click(function () {

            console.log($(".pagenumpro:last").val());

            if ($(".pagenumpro:last").val() <= $(".total-pagepro:last").val()) {

                var pagenum = parseInt($(".pagenumpro:last").val()) + 1;
                getresultpro('<?= $this->url->get("admin/propositionload") ?>?page=' + pagenum);
            }

        });

        function getresultli(url) {
            $.ajax({
                url: url,
                type: "GET",
                data: {rowcount: $("#rowcountli").val()},
                beforeSend: function () {
                    $('#load').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeIn(0);
                },
                complete: function () {
                    $('#load').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeOut(0);
                },
                success: function (data) {
                    $("#loadlivre").append(data);
                },
                error: function () {}
            });
        }

        $("#Li").click(function () {

            console.log("bonjour");
            if (livre == 0) {

                $.ajax({
                    url: "<?= $this->url->get("admin/livreload") ?>",
                    type: 'GET',
                    beforeSend: function () {
                        $('#load').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeIn(0);
                    },
                    complete: function () {
                        $('#load').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeOut(0);
                    },
                    success: function (data) {
                        $("#loadlivre").append(data);

                    }


                });
                livre = 1;
            }
        });

        $("#livreload").click(function () {

            console.log($(".pagenumli:last").val());

            if ($(".pagenumli:last").val() <= $(".total-pageli:last").val()) {

                var pagenum = parseInt($(".pagenumli:last").val()) + 1;
                getresultli('<?= $this->url->get("admin/livreload") ?>?page=' + pagenum);
            }

        });

        $('#loadlivre').on('click', '.supress', function () {
            var IdLi = $(this).attr('value');

            console.log("bonjour");
            $.ajax({
                url: "<?= $this->url->get("admin/supress") ?>?IdLi=" + IdLi,
                type: 'GET',
                beforeSend: function () {
                    $('#load').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeIn(0);
                },
                complete: function () {
                    $('#load').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeOut(0);
                },
                success: function (data) {

                    $('#loadlivre > #' + IdLi).html('<td></td><td></td><td></td><td></td><td></td><td></td>');
                }


            });


        });

        $('#loadlivre').on('click', '.update', function () {
            var IdLi = $(this).attr('value');

            console.log("bonjour");
            $.ajax({
                url: "<?= $this->url->get("admin/updatesearch") ?>?IdLi=" + IdLi,
                type: 'GET',
                beforeSend: function () {
                    $('#load').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeIn(0);
                },
                complete: function () {
                    $('#load').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeOut(0);
                },
                success: function (data) {

                    $('#modif').html(data);
                }


            });


        });

        $('#loadpro').on('click', '.rejectpro', function () {
            var IdPro = $(this).attr('value');
            $(this).prop("disabled", true);
            console.log("bonjour");
            $.ajax({
                url: "<?= $this->url->get("admin/rejectpro") ?>?IdPro=" + IdPro,
                type: 'GET',
                beforeSend: function () {
                    $('#load').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeIn(0);
                },
                complete: function () {
                    $('#load').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeOut(0);
                },
                success: function (data) {


                }


            });


        });

        $('#loadpro').on('click', '.acceptpro', function () {
            var IdPro = $(this).attr('value');
            $(this).prop("disabled", true);
            console.log("bonjour");
            $.ajax({
                url: "<?= $this->url->get("admin/acceptpro") ?>?IdPro=" + IdPro,
                type: 'GET',
                beforeSend: function () {
                    $('#load').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeIn(0);
                },
                complete: function () {
                    $('#load').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeOut(0);
                },
                success: function (data) {


                }


            });


        });


        $("#search").keyup(function () {



            $("#loader_1").removeClass("hide");
            var pourc = encodeURIComponent($("#search").val());
            $.ajax({
                url: "<?= $this->url->get("admin/searchlivre") ?>?pourc=" + pourc,
                type: 'GET',
                success: function (html) {
                    $("#loadlivre").html(html);
                    $("#livreload").prop("disabled", true);
                }
            });
        });



    });
</script>