<div class="col-lg-3">

    <?php $this->flashSession->output() ?>
    <?php foreach ($auteur as $value): ?>
        <h1 class="my-4" style=""> 
            <i style="font-size:40px; color:#ffc166;z-index:10; position:absolute;top:40%; right:9%;" data-toggle="collapse" data-target="#save"  id="photo" class="fa fa-3x fa-pencil-square"></i>
            <img height="220px" style="border-radius:50px; " src="<?= $this->url->getBaseUri() . $value->getProfil(); ?>">
        </h1>
    <?php endforeach; ?>
    <hr/>

    <form method="post" action="profil" enctype="multipart/form-data">
        <div class="collapse" id="save">
            <input type="file" name="profil" class="form-control" style="" required="" accept="jpg"/>
            <button class="btn btn-lg form-control btn-primary pull-right" role="button">Changer</button>
            <hr/>
        </div>
    </form>
    <hr/>

    <div class="list-group">
        <h5> <i style="font-size:20px; color:#ffc166; " class="fa fa-2x fa-star"></i><b>Favoris</b></h5>
        <a href="#" class="list-group-item">Molière</a>
        <a href="#" class="list-group-item">Le livre de la jungle</a>
        <a href="#" class="list-group-item">Tomasino</a>
    </div>

</div>
<!-- /.col-lg-3 -->

<div class="col-lg-9">



    <div class="jumbotron">
        <?php foreach ($user as $user): foreach ($auteur as $auteur): ?>

                <h1><?= $user->getNom() . " " . $user->getPrenom() ?></h1>
                <p class="lead"><?= $auteur->getBibiographie() ?></p><br/>
                <p class="lead">Age: <span><?= date("Y") - date("Y", $user->getDateNaiss()) ?></span>ans</p>
                <p class="lead">Mail: <span><?= $user->getMail() ?></span></p>
            <?php endforeach;
        endforeach;
        ?>  
        <p><a class="btn btn-lg btn-primary" href="<?= $this->url->get("auteur/modifier"); ?>" role="button">Changer mes informations</a></p>
    </div>
    <div class="row">
        <button class="btn btn-lg col-lg-9 jumbotron btn-primary" data-toggle="modal" data-target="#exampleModal" role="button">Publier un livre en tant qu'auteur</button>
    </div>

    <h3 class="card-title"> <b>Mes livres prêtés </b></h3> 

    <div class="row">
        <div class="col-md-4 mb-4">
            <div class="card h-100">
                <div class="card-body"><h4 class="card-title">Card One</h4> 
                    <img height="120px" src="<?= $this->url->getBaseUri(); ?>public/img/1.jpg">
                    <h7 class="text-muted"> <i class="fa fa-eye"></i> 2 vues</h7>
                    <p class="card-text"> maxime minus quam molestias</p>
                </div>
                <div class="card-footer" >
                    <a href="#" class="btn btn-warning"> <i class="fa fa-star"></i></a>
                    <a href="#" class="btn btn-primary"> <i class="fa fa-book"></i> lire</a>
                    <i class="fa fa-clock-o"></i> 1h 30min 00s
                </div>
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
            </div>
            <br/>
        </div>

        <div class="col-md-4 mb-4">
            <div class="card h-100">
                <div class="card-body"><h4 class="card-title">Card One</h4> 
                    <img height="120px" src="<?= $this->url->getBaseUri(); ?>public/img/1.jpg">
                    <h7 class="text-muted"> <i class="fa fa-eye"></i> 2 vues</h7>
                    <p class="card-text"> maxime minus quam molestias</p>
                </div>
                <div class="card-footer" >
                    <a href="#" class="btn btn-warning"> <i class="fa fa-star"></i></a>
                    <a href="#" class="btn btn-primary"> <i class="fa fa-book"></i> lire</a>
                    <i class="fa fa-clock-o"></i> 1h 30min 00s
                </div>
                <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
            </div>
            <br/>
        </div>
    </div>

    <br/>
    <h3 class="card-title"> <b>Mes Publications </b></h3> 

    <div class="row" id="pub">
<?= $pub ?>
    </div>
    <p id="loadpub"></p>
    <div class="collapse" id="likeby">


    </div>
    <hr/>
    <button type="button" id="pubload" class="btn btn-info">
        <i class="fa fa-1x fa-eye"></i> Voir plus
    </button>

    <hr/>
</div>





<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Créer un compte</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div> 

            <div class="modal-body">
                <form  action="<?= $this->url->get("publication/publier"); ?>" method="post" enctype="multipart/form-data">
                    <p class="lead"><b>Publié un livre</b></p>

                    <input type="text" name="titre" size="25" class="form-control" placeholder="Titre..." required>
                    <br/>

                    <textarea type="text" name="text" size="200" class="form-control"  required>Laissez un commentaire...</textarea>
                    <br/>

                    <div class="col-md-6 mb-4">
                        <h6><b>Photo de couverture du livre:</b></h6>
                        <label class="nav">
                            <i style="font-size:40px;" class=" col-sm-1 fa fa-2x fa-image"></i><input type="file" name="cover" style="display: none;"/>
                        </label>    
                    </div>  

                    <div class="col-md-6 mb-4">
                        <h6><b>Selectionner le livre (format TXT ou PDF ou WORD):</b></h6>
                        <label class="nav">
                            <i style="font-size:40px;" class=" col-sm-1 fa fa-2x fa-folder-open"></i><input type="file" name="lien" style="display: none;" multiple=""/>
                        </label>   
                    </div> 
                    <div class="modal-footer"><hr/>
                        <hr/>
                        <button class="btn btn-lg form-control btn-primary pull-right" role="button">publier</button>
                        <br/>
                    </div>
                </form>
            </div>


        </div>
    </div>
</div>
<script>
    $(function () {
        $('#pub').on('click', '.like', function () {

            var IdPub = $(this).attr('class').split(' ').slice(-1);
            console.log("bonjour");
            $.ajax({
                url: "<?= $this->url->get("default/like") ?>?IdPub=" + IdPub,
                type: 'GET',
                beforeSend: function () {
                    $('#load').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeIn(0);
                },
                complete: function () {
                    $('#load').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeOut(0);
                },
                success: function (data) {
                    console.log(data);
                    $("span.like" + IdPub).html(data);
                }


            });


        });

        $('#pub').on('click', '.likeby', function () {

            var IdPub = $(this).attr('class').split(' ').slice(-1);
            console.log("bonjour");
            $.ajax({
                url: "<?= $this->url->get("default/likeby") ?>?IdPub=" + IdPub,
                type: 'GET',
                beforeSend: function () {
                    $('#load').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeIn(0);
                },
                complete: function () {
                    $('#load').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeOut(0);
                },
                success: function (data) {
                    console.log(data);
                    $("#likeby").html(data);
                }


            });


        });

        $("#search").keyup(function () {



            $("#loader_1").removeClass("hide");
            var pourc = encodeURIComponent($("#search").val());
            $.ajax({
                url: "<?= $this->url->get("auteur/searchpub") ?>?pourc=" + pourc,
                type: 'GET',
                success: function (html) {
                    $("#loadpub").hide();
                    $("#pubload").prop("disabled", true);
                    $("#pub").html(html);
                }
            });
        });

        $('#pub').on('click', '.comment', function () {
            var IdPub = $(this).attr('id');

            $("#hidden").html('<input type="hidden" name="IdPub" value="' + IdPub + '">');
            $("#messload").attr('value', IdPub);
            $.ajax({
                url: "<?= $this->url->get("publication/messageload") ?>?IdPub=" + IdPub,
                type: 'GET',
                beforeSend: function () {
                    $('#loadmessage').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeIn(0);
                },
                complete: function () {
                    $('#loadmessage').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeOut(0);
                },
                success: function (data) {
                    $("#mess").html(data);
                }


            });


        });

        $('#modalmess').on('submit', '#formulaire', function (e) {
            e.preventDefault();
            var donne = $(this).serialize();
            $.ajax({
                url: "<?= $this->url->get("publication/addcomment") ?>",
                type: "POST",

                data: donne,
                beforeSend: function () {
                    $('#message').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeIn(0);
                    document.getElementById("ok").disabled = -1;
                },
                complete: function () {
                    $('#message').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeOut(0);
                    document.getElementById("ok").disabled = 0;
                },
                success: function (html) {
                    $('#message').html(html);
                }
            });

        });

        function getresultmessage(url) {
            $.ajax({
                url: url,
                type: "GET",
                data: {rowcount: $("#rowcountmess").val()},
                beforeSend: function () {

                    $('#loadmessage').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeIn(0);
                },
                complete: function () {
                    $('#loadmessage').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeOut(0);
                },
                success: function (data) {
                    $("#mess").append(data);
                },
                error: function () {}
            });
        }

        $('#pub').on('click', '.embed', function () {
            var IdPub = $(this).attr('class').split(' ').slice(-1);
            console.log("bonjour");
            $.ajax({
                url: "<?= $this->url->get("publication/vue") ?>?IdPub=" + IdPub,
                type: 'GET',
                beforeSend: function () {
                    $('#load').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeIn(0);
                },
                complete: function () {
                    $('#load').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeOut(0);
                },
                success: function (data) {
                    $("span." + IdPub).html(data);
                    $('#embed' + IdPub).gdocsViewer();
                }


            });


        });

        $('#modalmess').on('click', '#messload', function () {

            var IdPub = $(this).attr('value');
            if ($(".pagenummess:last").val() <= $(".total-pagemess:last").val()) {

                var pagenum = parseInt($(".pagenummess:last").val()) + 1;
                getresultmessage('<?= $this->url->get("publication/messageload") ?>?page=' + pagenum + '&IdPub=' + IdPub);
            }

        });

        function getresultpub(url) {
            $.ajax({
                url: url,
                type: "GET",
                data: {rowcount: $("#rowcountpub").val()},
                beforeSend: function () {
                    console.log($("#rowcountpub").val());
                    $('#loadpub').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeIn(0);
                },
                complete: function () {
                    $('#loadpub').html(' <i class="now-ui-icons loader_refresh spin" style=" font-size: 20px; " width="200px"></i> ').fadeOut(0);
                },
                success: function (data) {
                    console.log(data);
                    $("#pub").append(data);
                },
                error: function () {}
            });
        }

        $("#pubload").click(function () {

            if ($(".pagenumpub:last").val() <= $(".total-pagepub:last").val()) {

                var pagenum = parseInt($(".pagenumpub:last").val()) + 1;
                console.log(pagenum);
                getresultpub('<?= $this->url->get("auteur/pubload") ?>?page=' + pagenum);
            }

        });

    });
</script>

